---
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - config-data:/data/configdb
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
  mongo_seed:
    container_name: mongo_seed
    build: .
    depends_on:
      - mongodb

volumes:
  data:
  config-data:

networks:
  default:
    name: mongodb_network
